// demo/react/react.editor.tsx
// App.tsx
import { RevoGrid, Editor, type EditorType, type Editors } from '@revolist/react-datagrid';

/**
 * Custom editor component
 */
const Button = ({ close }: EditorType) => {
  return <button onClick={() => close()}>Close</button>
};

function App() {
  const MY_EDITOR = 'custom-editor';
  const columns = [
    {
      prop: 'name',
      name: 'First',
      editor: MY_EDITOR,
    },
  ];
  const source = [
    {
      name: '1',
      details: 'Item 1',
    },
  ];
  const gridEditors: Editors = { [MY_EDITOR]: Editor(Button) };
  return (
    <>
      <RevoGrid columns={columns} source={source} editors={gridEditors} />
    </>
  )
}

export default App;

// demo/svelte/svelte.editor.svelte
<script lang="ts">
  import {
    Editor,
    RevoGrid,
    Template,
    type ColumnRegular,
    type Editors,
    type EditorType,
  } from '@revolist/svelte-datagrid';
  import OperationCell from './svelte.cell.template.svelte';
  import OperationEditor from './svelte.editor.template.svelte';

  const OPERATION_EDITOR = 'operation';

  const source = [
    { name: 'Order 1', operation: 'Review' },
    { name: 'Order 2', operation: 'Archive' },
  ];

  const editors: Editors = {
    [OPERATION_EDITOR]: Editor(OperationEditor),
  };

  const columns: ColumnRegular[] = [
    { prop: 'name', name: 'Name' },
    {
      prop: 'operation',
      name: 'Operation',
      cellTemplate: Template(OperationCell),
      editor: OPERATION_EDITOR,
    },
  ];
</script>

<RevoGrid {source} {columns} {editors} />
