// demo/svelte/svelte.cell.svelte
<script lang="ts">
  import {
    RevoGrid,
    Template,
    type ColumnRegular,
  } from '@revolist/svelte-datagrid';
  import OperationCell from './svelte.cell.template.svelte';

  const source = [
    { name: 'Order 1', status: 'Pending', operation: 'Review' },
    { name: 'Order 2', status: 'Done', operation: 'Archive' },
  ];

  const columns: ColumnRegular[] = [
    { prop: 'name', name: 'Name' },
    { prop: 'status', name: 'Status' },
    {
      prop: 'operation',
      name: 'Operation',
      cellTemplate: Template(OperationCell),
    },
  ];
</script>

<RevoGrid {source} {columns} />

// demo/react/react.cell.tsx
// App.tsx
import { type ColumnDataSchemaModel, RevoGrid, Template } from '@revolist/react-datagrid';

/**
 * Custom cell component
 */
const Cell = ({ value }: Partial<ColumnDataSchemaModel>) => {
  return <div><strong>{value}</strong></div>;
};

function App() {
  const columns = [
    {
      prop: 'name',
      name: 'First',
      cellTemplate: Template(Cell),
    },
  ];
  const source = [
    {
      name: '1',
      details: 'Item 1',
    },
  ];
  return (
    <>
      <RevoGrid columns={columns} source={source} />
    </>
  )
}

export default App;
