// demo/angular/angular.simple-grid.ts
import { Component } from '@angular/core'
import { RevoGrid } from '@revolist/angular-datagrid'

@Component({
  selector: 'app-simple-grid',
  standalone: true,
  imports: [RevoGrid],
  template: `<revo-grid [columns]="columns" [source]="source" />`,
})
export class SimpleGridComponent {
  source = [{ name: '1' }, { name: '2' }, { name: '3' }]
  columns = [{ prop: 'name' }]
}

// demo/react/react.simple-grid.tsx
import { RevoGrid } from '@revolist/react-datagrid'
import { useState } from 'react'

const columns = [{ prop: 'name' }]
function App() {
  const [source] = useState([
    { name: '1' }, { name: '2' }, { name: '3' }
  ])
  return (
    <>
      <RevoGrid columns={columns} source={source} />
    </>
  )
}

export default App
